(define build-sample-tree ('
    (define root '())
    (set root (insert-set 24 root))
    (set root (insert-set 13 root))
    (set root (insert-set 42 root))
    (set root (insert-set 6 root))
    (set root (insert-set 11 root))
    (set root (insert-set 101 root))
    (set root (insert-set 33 root))))
(build-sample-tree)
(say 'preorder-traversal)
(pre-order root)
(say 'inorder-traversal)
(foreach-set say root)